# Site settings
title: Abhinav Mehta Weblog
email: developeratworks@gmail.com
description: "my ramblings"

source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
assets:      /assets
include:     []
exclude:     ['auth']
keep_files:  ['.git']
gems:        []
timezone:    'Asia/Kolkata'
encoding:    'utf-8'

future:      true
show_drafts: nil
limit_posts: 0
highlighter: pygments

relative_permalinks: true
permalink:     none
paginate_path: 'page:num'
paginate:      1

markdown:      kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
textile_ext:   textile

excerpt_separator: "\n\n"

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     ""
url:         http://abhinavmehta.com
lsi:         false

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style
